version: 2.1

build-images: &build-images
  - terraform
  - kubectl
  - hashicorp

executors:
  lint:
    docker:
      - image: hadolint/hadolint:v1.17.0-debian

commands:
  lint:
    description: "Lint a dockerfile"
    parameters:
      directory:
        type: string
    steps:
      - run: hadolint << parameters.directory >>/Dockerfile

  build:
    description: "Build a directory using make"
    parameters:
      directory:
        type: string
    steps:
      - run: |
            make -C << parameters.directory >> build_version
            make -C << parameters.directory >> save

  push-setup:
    description: "Setup a machine to do Docker pushes"
    steps:
      - run: apk add --no-cache build-base
      - setup_remote_docker:
          docker_layer_caching: true
      - checkout
      - attach_workspace:
          at: ./
      - run: |
            docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD"

  push:
    description: "Push a directory using make"
    parameters:
     directory:
       type: string
    steps:
      - run: docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD"
      - run: |
            make -C << parameters.directory >> load
            make -C << parameters.directory >> push_version

jobs:
  lint:
    executor: lint
    steps:
      - checkout
      - lint:
          directory: terraform
      - lint:
          directory: kubectl
      - lint:
          directory: hashicorp
  
  build-images:
    description: "Images that will be used to run applications"
    machine:
      docker_layer_caching: true
    steps:
      - checkout
      - build:
          directory: terraform
      - build:
          directory: kubectl
      - build: 
          directory: hashicorp
      - persist_to_workspace:
          root: ./
          paths: *build-images

  push-images:
    docker:
      - image: docker:18.09.7
    steps:
      - push-setup
      - push:
          directory: terraform
      - push:
          directory: kubectl
      - push:
          directory: hashicorp


workflows:
  version: 2.1
  build_everything:
    jobs:
      - lint
      - build-images:
          requires:
            - lint
      - push-images:
          requires:
            - build-images