version: 2.1

build-images: &build-images
  - terraform

executors:
  lint:
    docker:
      - image: hadolint/hadolint:v1.16.0-debian

commands:
  lint:
    description: "Lint a dockerfile"
    parameters:
      directory:
        type: string
    steps:
      - run: hadolint << parameters.directory >>/Dockerfile

jobs:
  lint:
    executor: lint
    steps:
      - checkout
      - lint:
          directory: terraform

  test:
    machine: true
    steps:
      - checkout
      - test:
          directory: terraform

workflows:
  version: 2.1
  build:
    jobs:
      - lint