version: 2.1

build-images: &build-images
  - terraform

executors:
  lint:
    docker:
      - image: hadolint/hadolint:v1.16.0-debian

  build-docker:
    environment:
      IMAGE_NAME: marcincuber/terraform
    docker:
      - image: circleci/buildpack-deps:stretch

commands:
  lint:
    description: "Lint a dockerfile"
    parameters:
      directory:
        type: string
    steps:
      - run: hadolint << parameters.directory >>/Dockerfile

jobs:
  lint:
    executor: lint
    steps:
      - checkout
      - lint:
        directory: terraform
  build:
    executor: build-docker
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build Docker image
          command: |
            docker build -t $IMAGE_NAME:latest .
        directory: terraform

workflows:
  version: 2.1
  build:
    jobs:
      - lint
      - build:
        filters:
          branches:
            only: master