version: 2.1

build-images: &build-images
  - terraform

executors:
  lint:
    docker:
      - image: hadolint/hadolint:v1.16.0-debian

commands:
  lint:
    description: "Lint a dockerfile"
    parameters:
      directory:
        type: string
    steps:
      - run: hadolint << parameters.directory >>/Dockerfile

jobs:
  lint:
    executor: lint
    steps:
      - checkout
      - lint:
          directory: terraform

  test:
    machine: true
    steps:
      - checkout
      - test:
          directory: terraform

  build:
    description: "Build a directory using make"
    environment:
      IMAGE_NAME: marcincuber/terraform
    parameters:
      directory:
        type: string
    steps:
      - run:
        command: docker build -t $IMAGE_NAME:latest .

  build-images:
    description: "Images that will be used to run applications"
    machine:
      docker_layer_caching: true
    steps:
      - checkout
      - build:
          directory: terraform
      - persist_to_workspace:
          root: ./
          paths: *build-images

workflows:
  version: 2.1
  build:
    jobs:
      - lint
      - build-images:
          requires:
            - lint